"""
Project Euler 12: Find the value of the first triangle number to have over five hundred divisors
The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55
Let us list the factors of the first seven triangle numbers:
"""

import util

n = 1

while len(util.factors(util.trianglar(n))) <= 500:
	n += 1
print n, util.trianglar(n)