"""
Project Euler 29: Find the number of distinct terms in the sequence generated by a**b
"""

distinct_terms = set()

limit = 100

for a in range(2,limit+1):
	for b in range(2,limit+1):
		distinct_terms.add(a**b)

print len(distinct_terms)